mercari-build/mercari-build-training

document/step1.en.md
document/step1.ja.md
document/tips.en.md

- Tips (EN)
- Add git install links

Add en docs and git install links

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

- PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md

Add pr template and CONTRIBUTING.md

---

document/team-hackathon.en.md

Team Hackathon Doc EN

---

document/step3.en.md
document/step3.ja.md

Fix docs for GET and POST in STEP3

---

document/step3.en.md

There is a code block missing in step3.en.md (STEP3 Section 6) while I found it available in step3.ja.md. 
https://github.com/mercari-build/mercari-build-training-2022/blob/main/document/step3.ja.md?plain=1#L145-L154

Fix missing code block in step3.en.md

---

document/step3.en.md
document/step3.ja.md
go/app/main.go
python/main.py
typescript/simple-mercari-web/src/App.tsx
typescript/simple-mercari-web/src/components/ItemList/ItemList.tsx
typescript/simple-mercari-web/src/components/Listing/Listing.tsx

`image` column was ambiguous in the previous docs as to whether it was a file or a path on the backend, so this PR specifies that the request parameter `-image` takes a File from local and the database column is a filename `image_filename: string`.
This PR also modifies the frontend to make sure that an image is uploaded, and sets `formDataType` for data types for the http POST method.

[STEP3, STEP5] Change image type and clarify documents

---

typescript/simple-mercari-web/src/components/Listing/Listing.tsx

Changes in the file upload were not handled properly so new functions are added to deal with value changes and file changes respectively

[STEP5] Fix onChange functions for value and file and log http statusText on console

---

document/step1.en.md
document/step1.ja.md

* delete todo
* fork first (for tutorial session)

Change step1 order and delete todo

---

typescript/simple-mercari-web/src/components/ItemList/ItemList.tsx

Fix data.items in ItemList.tsx

---

document/step4.en.md

- Added the Section 1 to Step 4 document to make it the same as Japanese version
Note: I replaced the reference link with the english version in the Docker official documentation.

Add Section 1 to Step 4 document (ENG ver.)

---

README.md
document/08-docker-compose.ja.md

Add todo 2024 2

---

document/01-git.en.md
document/01-git.ja.md
document/03-api.en.md
document/03-api.ja.md
document/04-database.en.md
document/04-database.ja.md
document/05-docker.en.md
document/07-frontend.en.md
document/08-docker-compose.en.md
python/main.py
typescript/simple-mercari-web/src/components/ItemList/ItemList.tsx

This PR contains some small fixes in the documentation. I'd appreciate you to review when you have time :bow:
- unify mixed `image_name` and `image_filename` with `image_name` in https://github.com/mercari-build/mercari-build-training/commit/abc52fddd35aef905deadcfc86331702e4118db1
- rename the table name from `category` to `categories` in https://github.com/mercari-build/mercari-build-training/commit/a417217901be7293e2816dc97d2ad215d373c96d
- the existing `items` table is a plural form.
- I don't think mixed naming convention is good.
- fix typos in https://github.com/mercari-build/mercari-build-training/commit/f05800cc3bfcabd52a6af80a42316c3a9aaec22d 

change(docs): apply small fixes

---

README.md

Add new contents link: Algorithm

Update EXTRA1 link

---

document/01-git.en.md
document/01-git.ja.md
document/02-local-env.en.md
document/02-local-env.ja.md
document/05-docker.en.md
document/05-docker.ja.md
document/06-ci.en.md
document/06-ci.ja.md
document/tips.ja.md
go/app/main.go
python/.gitignore

SSIA
You can cherry-pick some commits if you need.

Fix code and docs to improve readability and strictness

---

document/02-local-env.en.md
document/02-local-env.ja.md
go/app/main.go

* Add comment for creating python virtual environment.
* Go: 201 --> 200, because we don't return new resource location.
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201

Add some comment for following up setup environment

---

.github/workflows/build.yml

- Add build.yaml to workflow
- Resolve https://github.com/mercari-build/mercari-build-training/issues/165

Add build.yml

---

document/03-api.en.md
document/03-api.ja.md

Curlのインストール方法がわからないというメンバーが複数いたので、
Curlのインストール方法とバージョン確認方法を追加しました。
ご確認お願いします。

Curlのインストール方法を追加

---

document/03-api.ja.md
document/05-docker.en.md
document/05-docker.ja.md
document/06-ci.en.md
document/06-ci.ja.md
document/07-frontend.en.md
document/07-frontend.ja.md

些細な部分なのですが、documentのNext部分の記述について修正を行いました。

documentのNext周りの修正

---

typescript/simple-mercari-web/src/components/ItemList/ItemList.tsx

Reverts mercari-build/mercari-build-training#205
https://github.com/mercari-build/mercari-build-training/pull/205#issuecomment-1963382677

Revert "[step7] fix setItems() properties"

---

document/05-docker.en.md
document/05-docker.ja.md

step-5: add explanation of docker build and call API

---

go/app/app.go

SSIA
ref: https://mercari.slack.com/archives/C04SV7GD5U1/p1740751898796939?thread_ts=1740714888.782659&cid=C04SV7GD5U1

change(go): remove slog context funcs

---

go/app/app.go

SSIA
ref: https://mercari.slack.com/archives/C04SV7GD5U1/p1740749778255669?thread_ts=1740714888.782659&cid=C04SV7GD5U1

change(app): add JSON tag for persistent

---

go/app/app.go

As blank import is a kind of trap, this PR adds it with a comment.

change(go): add comment for sqlite3

---

document/04-api.en.md
document/04-api.ja.md

change(document):add explanation for abstraction

---

document/07-docker.en.md
document/07-docker.ja.md
document/09-frontend.en.md
document/09-frontend.ja.md
document/10-docker-compose.en.md

SSIA
ref: https://mercari.slack.com/archives/C04SV7GD5U1/p1740789587038829?thread_ts=1740788863.588309&cid=C04SV7GD5U1

change(document): replace step3 mentioning API changes with step4

---

document/04-api.en.md
document/04-api.ja.md

STEP4の最後で突如idの概念が出てくるのをresponseから消す
* delete id
* add decription

Update step4-5 document

---

python/main.py

remove category field

---

python/main.py

change(python): remove category from item insertion

---

document/04-api.en.md
document/04-api.ja.md
go/app/infra.go
go/app/server.go
python/main.py

change(document): update wrong comments

---

README.md
document/01-git.en.md
document/01-git.ja.md

update <your github id> to your_github_id to avoid escape

---

document/01-git.en.md
document/01-git.ja.md

Fix brew link

---

document/06-testing.en.md
document/06-testing.ja.md

docs: update pytest documentation links & format

---

document/10-docker-compose.en.md
document/10-docker-compose.ja.md

update docker image name (remove 2024 from name, align with STEP 7)

update STEP 10 documentation

---

.github/workflows/build.yml

feat(ci): support multi platform
